# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-online-issues
  version: "0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_online_issues-${{ version }}.tar.gz
  sha256: d6bbf1dc38a77dfeb23a4b6c0621e1891623c4e523d137bbeb916464c2182f1a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs >=0.4
    - hatchling >=1.25
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4
    - django-stubs-ext
    - markdown >=3.8.2
    - requests >=2.32.5

tests:
  - python:
      imports:
        - issues
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A reusable Django app for collecting and reporting user-submitted issues (tickets). It provides a view and a form to submit tickets and forwards them to configurable backends like GitLab, GitHub, email, or simply the development console.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/saxix/django-online-issues

extra:
  recipe-maintainers:
    - rxm7706
